### ISSUE TITLE
script stopped working after game update

### ISSUE THREAD

**Issue by sando21** [Jrpl/Bitburner-Scripts#5]
When runnung hack-manager, i get this. was working ok before game update

RUNTIME ERROR
hack-manager.js@home

growthAnalyze: Invalid argument: growth must be numeric and >= 1, is Infinity.

Stack:
hack-manager.js:L277@Module.main

**Comment by Riley-H-99** [comment]
I believe I found the issue, that behavior could arise from a server with zero money available being targeted. I added a conditional check to make sure the growth being calculated is finite and I added a check to make sure a server has money available to be targeted. Let me know if this problem persists.

**Comment by sando21** [comment]
Running ok now, thanks for fixing it
