### ISSUE TITLE
1ms sleep loop after a successful cycle

### ISSUE THREAD

**Issue by Itsthereaper** [Jrpl/Bitburner-Scripts#6]
So ill start this out by saying im entirely new to java and scripting in general so I could be doing something wrong. The issue im having is that i run hack-manager.js and it works as intended for the first and sometimes even the second cycle, but randomly at the beginning of another cycle it will enter a 1ms loop and then do nothing for the rest of the time it runs. Could this be caused by me not having enough ram on the home system? Im pretty stumped on how to solve it.

**Comment by Itsthereaper** [comment]
hack-manager.js
sleep: Sleeping for 1 milliseconds

getServerMaxRam: returned 2.00GB

getServerUsedRam: returned 0.00B

getServerMaxRam: returned 2.00GB

getServerUsedRam: returned 0.00B

sleep: Sleeping for 1 milliseconds

getServerMaxRam: returned 2.00GB

getServerUsedRam: returned 0.00B

getServerMaxRam: returned 2.00GB

getServerUsedRam: returned 0.00B

sleep: Sleeping for 1 milliseconds

getServerMaxRam: returned 2.00GB

getServerUsedRam: returned 0.00B

getServerMaxRam: returned 2.00GB

getServerUsedRam: returned 0.00B

sleep: Sleeping for 1 milliseconds

getServerMaxRam: returned 2.00GB

getServerUsedRam: returned 0.00B

getServerMaxRam: returned 2.00GB

getServerUsedRam: returned 0.00B

sleep: Sleeping for 1 milliseconds

getServerMaxRam: returned 2.00GB

getServerUsedRam: returned 0.00B

getServerMaxRam: returned 2.00GB

getServerUsedRam: returned 0.00B

sleep: Sleeping for 1 milliseconds

getServerMaxRam: returned 2.00GB

getServerUsedRam: returned 0.00B

getServerMaxRam: returned 2.00GB

getServerUsedRam: returned 0.00B

sleep: Sleeping for 1 milliseconds

getServerMaxRam: returned 2.00GB

getServerUsedRam: returned 0.00B

getServerMaxRam: returned 2.00GB

getServerUsedRam: returned 0.00B

sleep: Sleeping for 1 milliseconds

getServerMaxRam: returned 2.00GB

getServerUsedRam: returned 0.00B

getServerMaxRam: returned 2.00GB

getServerUsedRam: returned 0.00B

sleep: Sleeping for 1 milliseconds

getServerMaxRam: returned 2.00GB

getServerUsedRam: returned 0.00B

getServerMaxRam: returned 2.00GB

getServerUsedRam: returned 0.00B

sleep: Sleeping for 1 milliseconds

getServerMaxRam: returned 2.00GB

getServerUsedRam: returned 0.00B

getServerMaxRam: returned 2.00GB

getServerUsedRam: returned 0.00B

sleep: Sleeping for 1 milliseconds


This is a log of what happens on a cycle that causes it to fail. It just sits at that last line and does nothing.

**Comment by Itsthereaper** [comment]
I have it zeroed down to user error lol.

**Comment by Riley-H-99** [comment]
Would you please tell me what the user error might’ve been. I’d love to add
to the documentation to clarify this behavior in the future.

**Comment by Itsthereaper** [comment]
So im not 100% sure that this is what was doing it the whole time, but. Im assuming that somehow, as i was still in the beginning of the game, at some point while the script was running, upgrades would drastically change the time needed to complete the hack, grow, or weaken. Either that, or something was changing while the script was trying to create a cycle and would freeze up.

**Comment by Itsthereaper** [comment]
i have not been able to reproduce the problem since i upgraded my home server to 128gigs+ of ram
